/**
 * Transactions API
 * This is an API designed for a bank transactions coding challenge. It has not been properly tested and was designed more as a proof of concept
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maxcan7@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.TransactionsApi) {
      root.TransactionsApi = {};
    }
    root.TransactionsApi.Balances = factory(root.TransactionsApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Balances model module.
   * @module model/Balances
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Balances</code>.
   * @alias module:model/Balances
   * @class
   * @param accountNr {Number} 
   * @param balance {Number} 
   */
  var exports = function(accountNr, balance) {
    var _this = this;

    _this['account nr'] = accountNr;
    _this['balance'] = balance;
  };

  /**
   * Constructs a <code>Balances</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Balances} obj Optional instance to populate.
   * @return {module:model/Balances} The populated <code>Balances</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('account nr')) {
        obj['account nr'] = ApiClient.convertToType(data['account nr'], 'Number');
      }
      if (data.hasOwnProperty('balance')) {
        obj['balance'] = ApiClient.convertToType(data['balance'], 'Number');
      }
    }
    return obj;
  }

  /**
   * @member {Number} account nr
   */
  exports.prototype['account nr'] = undefined;
  /**
   * @member {Number} balance
   */
  exports.prototype['balance'] = undefined;



  return exports;
}));


