/**
 * Transactions API
 * This is an API designed for a bank transactions coding challenge. It has not been properly tested and was designed more as a proof of concept
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maxcan7@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Balances'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Balances'));
  } else {
    // Browser globals (root is window)
    if (!root.TransactionsApi) {
      root.TransactionsApi = {};
    }
    root.TransactionsApi.Transactions = factory(root.TransactionsApi.ApiClient, root.TransactionsApi.Balances);
  }
}(this, function(ApiClient, Balances) {
  'use strict';




  /**
   * The Transactions model module.
   * @module model/Transactions
   * @version 1.0.0
   */

  /**
   * Constructs a new <code>Transactions</code>.
   * @alias module:model/Transactions
   * @class
   * @param reference {Number} 
   * @param amount {Number} 
   * @param accountNr {module:model/Balances} 
   */
  var exports = function(reference, amount, accountNr) {
    var _this = this;

    _this['reference'] = reference;
    _this['amount'] = amount;
    _this['account nr'] = accountNr;
  };

  /**
   * Constructs a <code>Transactions</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Transactions} obj Optional instance to populate.
   * @return {module:model/Transactions} The populated <code>Transactions</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('reference')) {
        obj['reference'] = ApiClient.convertToType(data['reference'], 'Number');
      }
      if (data.hasOwnProperty('amount')) {
        obj['amount'] = ApiClient.convertToType(data['amount'], 'Number');
      }
      if (data.hasOwnProperty('account nr')) {
        obj['account nr'] = Balances.constructFromObject(data['account nr']);
      }
    }
    return obj;
  }

  /**
   * @member {Number} reference
   */
  exports.prototype['reference'] = undefined;
  /**
   * @member {Number} amount
   */
  exports.prototype['amount'] = undefined;
  /**
   * @member {module:model/Balances} account nr
   */
  exports.prototype['account nr'] = undefined;



  return exports;
}));


