/**
 * Transactions API
 * This is an API designed for a bank transactions coding challenge. It has not been properly tested and was designed more as a proof of concept
 *
 * OpenAPI spec version: 1.0.0
 * Contact: maxcan7@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Transactions'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Transactions'));
  } else {
    // Browser globals (root is window)
    if (!root.TransactionsApi) {
      root.TransactionsApi = {};
    }
    root.TransactionsApi.BankAdminsApi = factory(root.TransactionsApi.ApiClient, root.TransactionsApi.Transactions);
  }
}(this, function(ApiClient, Transactions) {
  'use strict';

  /**
   * BankAdmins service.
   * @module api/BankAdminsApi
   * @version 1.0.0
   */

  /**
   * Constructs a new BankAdminsApi. 
   * @alias module:api/BankAdminsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the pushTransaction operation.
     * @callback module:api/BankAdminsApi~pushTransactionCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * pushes a transaction
     * Pushes a transaction
     * @param {Object} opts Optional parameters
     * @param {module:model/Transactions} opts.transactions Transaction reference to add
     * @param {module:api/BankAdminsApi~pushTransactionCallback} callback The callback function, accepting three arguments: error, data, response
     */
    this.pushTransaction = function(opts, callback) {
      opts = opts || {};
      var postBody = opts['transactions'];


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = null;

      return this.apiClient.callApi(
        '/transfer', 'POST',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
